# -*- coding: utf-8 -*-
"""OpenAI_CLIP_simple_implementation_Rico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/161jkHqaZMBN0gJloiPQ7IuFLnvHNUdFU

## Introduction

Given a query (raw text) like "pop-up message showing about free access	" or "a description page of shopping app", the model will retrieve the most relevant images:
"""

!pip install timm
!pip install transformers

import os
import cv2
import gc
import numpy as np
import pandas as pd
import itertools
from tqdm.autonotebook import tqdm
import albumentations as A
import matplotlib.pyplot as plt

import torch
from torch import nn
import torch.nn.functional as F
import timm
from transformers import DistilBertModel, DistilBertConfig, DistilBertTokenizer

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

!unzip /content/drive/MyDrive/trainImages.zip

!unzip /content/drive/MyDrive/testImages.zip -d /content/

!unzip /content/drive/MyDrive/validImages.zip -d /content/

folder_path = "/content/trainImages"

# Get the list of files in the folder
file_list = os.listdir(folder_path)

# Count the number of files
num_files = len(file_list)

print(f"Number of files in the folder: {num_files}")

"""# Show one image from dataset"""

from google.colab.patches import cv2_imshow

image = cv2.imread("/content/trainImages/57715.jpg")

image = cv2.imread("/content/testImages/55300.jpg")

cv2_imshow(image)

"""## Some pre-preocessing"""

# for train and validation
import pandas as pd

#if dataset == "8k":
df = pd.read_csv("captions.csv")
image_path = "/content/trainImages"
captions_path = "/content"

# for test
import pandas as pd

#if dataset == "8k":
df = pd.read_csv("captions.csv")
image_path = "/content/testImages"
captions_path = "/content"

# Debugging: Print image paths
for index, row in df.iterrows():
        image_filename = row['image']
        image_full_path = os.path.join(image_path, image_filename)
        print(f"Processing image: {image_full_path}")

df.head(10)

df.shape

"""## Config

*A note on config and CFG: I wrote the codes with python scripts and then converted it into a Jupyter Notebook. So, in case of python scripts, config is a normal python file where I put all the hyperparameters and in the case of Jupyter Notebook, its a class defined in the beginning of the notebook to keep all the hyperparameters.*
"""

class CFG:
    debug = False
    image_path = image_path
    captions_path = captions_path
    batch_size = 32
    num_workers = 2
    head_lr = 1e-3
    image_encoder_lr = 1e-4
    text_encoder_lr = 1e-5
    weight_decay = 1e-3
    patience = 1
    factor = 0.8
    epochs = 4
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model_name = 'resnet50'
    image_embedding = 2048
    text_encoder_model = "distilbert-base-uncased"
    text_embedding = 768
    text_tokenizer = "distilbert-base-uncased"
    max_length = 200

    pretrained = True # for both image encoder and text encoder
    trainable = True # for both image encoder and text encoder
    temperature = 1.0

    # image size
    size = 224

    # for projection head; used for both image and text encoders
    num_projection_layers = 1
    projection_dim = 256
    dropout = 0.1

"""## Utils"""

class AvgMeter:
    def __init__(self, name="Metric"):
        self.name = name
        self.reset()

    def reset(self):
        self.avg, self.sum, self.count = [0] * 3

    def update(self, val, count=1):
        self.count += count
        self.sum += val * count
        self.avg = self.sum / self.count

    def __repr__(self):
        text = f"{self.name}: {self.avg:.4f}"
        return text

def get_lr(optimizer):
    for param_group in optimizer.param_groups:
        return param_group["lr"]

"""## Dataset

As you can see in the tittle image of this article, we need to encode both images and their describing texts. So, the dataset needs to **return both images and texts**. Of course we are not going to feed raw text to our text encoder! We will use **DistilBERT** model (which is smaller than BERT but performs nearly as well as BERT) from **HuggingFace** library as our text encoder; so, we need to **tokenize** the sentences (captions) with DistilBERT tokenizer and then feed the token ids (input_ids) and the attention masks to DistilBERT. Therefore, the dataset needs to take care of the tokenization as well. Below you can see the dataset's code. Below that I'll explain the most important things that is happening in the code.

In the **\_\_init\_\_** we receive a tokenizer object which is actually a HuggingFace tokinzer; this tokenizer will be loaded when running the model. We are padding and truncating the captions to a specified max_length. In the **\_\_getitem\_\_** we will first load an encoded caption which is a dictionary with keys input_ids and attention_mask, make tensors out of its values and after that we will load the corresponding image, transform and augment it (if there is any!) and then we make it a tensor and put it in the dictionary with "image" as the key. Finally we put the raw text of the caption with the key "caption" in the dictionary only for visualization purposes.

I did not use additional data augmentations but you can add them if you want to improve the model's performance.
"""

class CLIPDataset(torch.utils.data.Dataset):
    def __init__(self, image_filenames, captions, tokenizer, transforms):
        """
        image_filenames and cpations must have the same length; so, if there are
        multiple captions for each image, the image_filenames must have repetitive
        file names
        """

        self.image_filenames = image_filenames
        self.captions = list(captions)
        self.encoded_captions = tokenizer(
            list(captions), padding=True, truncation=True, max_length=CFG.max_length
        )
        self.transforms = transforms

    def __getitem__(self, idx):
        item = {
            key: torch.tensor(values[idx])
            for key, values in self.encoded_captions.items()
        }

        image = cv2.imread(f"{CFG.image_path}/{self.image_filenames[idx]}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = self.transforms(image=image)['image']
        item['image'] = torch.tensor(image).permute(2, 0, 1).float()
        item['caption'] = self.captions[idx]

        return item


    def __len__(self):
        return len(self.captions)



def get_transforms(mode="train"):
    if mode == "train":
        return A.Compose(
            [
                A.Resize(CFG.size, CFG.size, always_apply=True),
                A.Normalize(max_pixel_value=255.0, always_apply=True),
            ]
        )
    else:
        return A.Compose(
            [
                A.Resize(CFG.size, CFG.size, always_apply=True),
                A.Normalize(max_pixel_value=255.0, always_apply=True),
            ]
        )

"""## Image Encoder

The image encoder code is straight forward. I'm using PyTorch Image Models library (timm) here which makes a lot of different image models available from ResNets to EfficientNets and many more. Here we will use a ResNet50 as our image encoder. You can easily use torchvision library to use ResNets if you don't want to install a new library.

The code encodes each image to a fixed size vector with the size of the model's output channels (in case of ResNet50 the vector size will be **2048**). This is the output after the nn.AdaptiveAvgPool2d() layer.
"""

class ImageEncoder(nn.Module):
    """
    Encode images to a fixed size vector
    """

    def __init__(
        self, model_name=CFG.model_name, pretrained=CFG.pretrained, trainable=CFG.trainable
    ):
        super().__init__()
        self.model = timm.create_model(
            model_name, pretrained, num_classes=0, global_pool="avg"
        )
        for p in self.model.parameters():
            p.requires_grad = trainable

    def forward(self, x):
        return self.model(x)

"""## Text Encoder

As I mentioned before, I'll use DistilBERT as the text encoder. Like its bigger brother BERT, two special tokens will be added to the actual input tokens: **CLS** and **SEP** which mark the start and end of a sentence. To grab the whole representation of a sentence (as the related BERT and DistilBERT papers point out) we use the final representations of the CLS token and we hope that this representation captures the overall meaning of the sentence (caption). Thinking it in this way, it is similar to what we did to images and converted them into a fixed size vector.

In the case of DistilBERT (and also BERT) the output hidden representation for each token is a vector with size **768**. So, the whole caption will be encoded in the CLS token representation whose size is 768.
"""

class TextEncoder(nn.Module):
    def __init__(self, model_name=CFG.text_encoder_model, pretrained=CFG.pretrained, trainable=CFG.trainable):
        super().__init__()
        if pretrained:
            self.model = DistilBertModel.from_pretrained(model_name)
        else:
            self.model = DistilBertModel(config=DistilBertConfig())

        for p in self.model.parameters():
            p.requires_grad = trainable

        # we are using the CLS token hidden representation as the sentence's embedding
        self.target_token_idx = 0

    def forward(self, input_ids, attention_mask):
        output = self.model(input_ids=input_ids, attention_mask=attention_mask)
        last_hidden_state = output.last_hidden_state
        return last_hidden_state[:, self.target_token_idx, :]

"""## Projection Head

I used [Keras code example implementation](https://keras.io/examples/nlp/nl_image_search/) of projection head to write the following in PyTorch.
Now that we have encoded both our images and texts into fixed size vectors (2048 for image and 768 for text) we need to bring (project) them into a **new world** (!) with **similar dimensions** for both images and texts in order to be able to compare them and push apart the non-relevant image and texts and pull together those that match. So, the following code will bring the 2048 and 768 dimensional vectors into a 256 (projection_dim) dimensional world, where we can **compare** them.

"embedding_dim" is the size of the input vector (2048 for images and 768 for texts) and "projection_dim" is the the size of the output vector which will be 256 for our case. For understanding the details of this part you can refer to the CLIP paper.
"""

class ProjectionHead(nn.Module):
    def __init__(
        self,
        embedding_dim,
        projection_dim=CFG.projection_dim,
        dropout=CFG.dropout
    ):
        super().__init__()
        self.projection = nn.Linear(embedding_dim, projection_dim)
        self.gelu = nn.GELU()
        self.fc = nn.Linear(projection_dim, projection_dim)
        self.dropout = nn.Dropout(dropout)
        self.layer_norm = nn.LayerNorm(projection_dim)

    def forward(self, x):
        projected = self.projection(x)
        x = self.gelu(projected)
        x = self.fc(x)
        x = self.dropout(x)
        x = x + projected
        x = self.layer_norm(x)
        return x

"""## CLIP

This part is where all the fun happens! I'll also talk about the loss function here. I translated some of the code from Keras code examples into PyTorch for writing this part. Take a look at the code and then read the explanation below this code block.

Here we will use the previous modules that we built to implement the main model. The \_\_init\_\_ function is self-explanatory. In the forward function, we first encode the images and texts separately into fixed size vectors (with different dimensionalities). After that, using separate projection modules we project them to that shared world (space) that I talked about previously. Here the encodings will become of similar shape (256 in our case). After that we will compute the loss. Again I recommend reading CLIP paper to get it better but I'll try my best to explain this part.

In **Linear Algebra**, one common way to measure if two vectors are of similar characteristics (they are like each other) is to calculate their **dot product** (multiplying the matching entries and take the sum of them); if the final number is big, they are alike and if it is small they are not (relatively speaking)!

Okay! What I just said is the most important thing to have in mind to understand this loss function. Let's continue. We talked about two vectors, but, what do we have here? We have image_embeddings, a matrix with shape (batch_size, 256) and text_embeddings with shape (batch_size, 256). Easy enough! it means we have two groups of vectors instead of two single vectors. How do we measure how similar two groups of vectors (two matrices) are to each other? Again, with dot product (@ operator in PyTorch does the dot product or matrix multiplication in this case). To be able to multiply these two matrices together, we transpose the second one. Okay, we get a matrix with shape (batch_size, batch_size) which we will call logits. (temperature is equal to 1.0 in our case, so, it does not make a difference. You can play with it and see what difference it makes. Also look at the paper to see why it is here!).

I hope you are still with me! If not it's okay, just review the code and check their shapes. Now that we have our logits, we need targets. I need to say that there is a more straight forward way to obtain targets but I had to do this for our case (I'll talk about why in a next paragraph).

Let's consider what we hope that this model learns: **we want it to learn "similar representations (vectors)" for a given image and the caption describing it. Meaning that either we give it an image or the text describing it, we want it to produce same 256 sized vectors for both.**

#### Check the cell below this code block for the continue of the explanations
"""

class CLIPModel(nn.Module):
    def __init__(
        self,
        temperature=CFG.temperature,
        image_embedding=CFG.image_embedding,
        text_embedding=CFG.text_embedding,
    ):
        super().__init__()
        self.image_encoder = ImageEncoder()
        self.text_encoder = TextEncoder()
        self.image_projection = ProjectionHead(embedding_dim=image_embedding)
        self.text_projection = ProjectionHead(embedding_dim=text_embedding)
        self.temperature = temperature

    def forward(self, batch):
        # Getting Image and Text Features
        image_features = self.image_encoder(batch["image"])
        text_features = self.text_encoder(
            input_ids=batch["input_ids"], attention_mask=batch["attention_mask"]
        )
        # Getting Image and Text Embeddings (with same dimension)
        image_embeddings = self.image_projection(image_features)
        text_embeddings = self.text_projection(text_features)

        # Calculating the Loss
        logits = (text_embeddings @ image_embeddings.T) / self.temperature
        images_similarity = image_embeddings @ image_embeddings.T
        texts_similarity = text_embeddings @ text_embeddings.T
        targets = F.softmax(
            (images_similarity + texts_similarity) / 2 * self.temperature, dim=-1
        )
        texts_loss = cross_entropy(logits, targets, reduction='none')
        images_loss = cross_entropy(logits.T, targets.T, reduction='none')
        loss =  (images_loss + texts_loss) / 2.0 # shape: (batch_size)
        return loss.mean()


def cross_entropy(preds, targets, reduction='none'):
    log_softmax = nn.LogSoftmax(dim=-1)
    loss = (-targets * log_softmax(preds)).sum(1)
    if reduction == "none":
        return loss
    elif reduction == "mean":
        return loss.mean()

"""So, in the best case scenario, text_embeddings and image_embedding matricies should be the same because they are describing similar things. Let's think now: if this happens, what would the logits matrix be like? Let's see with a simple example!

So logits, in the best case, will be a matrix that if we take its softmax, will have 1.0s in the diagonal (An identity matrix to call it with fancy words!). As the loss function's job is to make model's predictions similar to targets (at least in most cases!), we want such a matrix as our target. That's the reason why we are calculating images_similarity and texts_similarity matrices in the code block above.

Now that we've got our targets matrix, we will use simple cross entropy to calculate the actual loss. I've written the full matrix form of cross entropy as a function which you can see in the bottom of the code block. Okay! We are done! Wasn't it simple?! Alright, you can ignore the next paragraph but if you are curious, there is an important note in that.

**Here's why I didn't use a simpler approach**: I need to admit that there's a simpler way to calculate this loss in PyTorch; by doing this: nn.CrossEntropyLoss()(logits, torch.arange(batch_size)). Why I did not use it here? For 2 reasons. 1- The dataset we are using has multiple captions for a single image; so, there is the possibility that two identical images with their similar captions exist in a batch (it is rare but it can happen). Taking the loss with this easier method will ignore this possibility and the model learns to pull apart two representations (assume them different)  that are actually the same. Obviously, we don't want this to happen so I calculated the whole target matrix in a way that takes care of these edge cases. 2- Doing it the way I did, gave me a better understanding of what is happening in this loss function; so, I thought it would give you a better intuition as well!

## Train

Here are some funtions to help us load train and valid dataloaders, our model and then train and evaluate our model on those. There's not much going on here; just simple training loop and utility functions
"""

def make_train_valid_dfs():
    dataframe = pd.read_csv(f"{CFG.captions_path}/captions.csv")
    max_id = dataframe["id"].max() + 1 if not CFG.debug else 100
    image_ids = np.arange(0, max_id)
    np.random.seed(42)
    valid_ids = np.random.choice(
        image_ids, size=int(0.2 * len(image_ids)), replace=False
    )
    train_ids = [id_ for id_ in image_ids if id_ not in valid_ids]
    train_dataframe = dataframe[dataframe["id"].isin(train_ids)].reset_index(drop=True)
    valid_dataframe = dataframe[dataframe["id"].isin(valid_ids)].reset_index(drop=True)
    return train_dataframe, valid_dataframe


def build_loaders(dataframe, tokenizer, mode):
    transforms = get_transforms(mode=mode)
    dataset = CLIPDataset(
        dataframe["image"].values,
        dataframe["caption"].values,
        tokenizer=tokenizer,
        transforms=transforms,
    )
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=CFG.batch_size,
        num_workers=CFG.num_workers,
        shuffle=True if mode == "train" else False,
    )
    return dataloader

"""Here's a handy function to train our model. There's not much happening here; just loading the batches, feeding them to the model and stepping the optimizer and lr_scheduler."""

def train_epoch(model, train_loader, optimizer, lr_scheduler, step):
    loss_meter = AvgMeter()
    tqdm_object = tqdm(train_loader, total=len(train_loader))
    for batch in tqdm_object:
        batch = {k: v.to(CFG.device) for k, v in batch.items() if k != "caption"}
        loss = model(batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if step == "batch":
            lr_scheduler.step()

        count = batch["image"].size(0)
        loss_meter.update(loss.item(), count)

        tqdm_object.set_postfix(train_loss=loss_meter.avg, lr=get_lr(optimizer))
    return loss_meter


def valid_epoch(model, valid_loader):
    loss_meter = AvgMeter()

    tqdm_object = tqdm(valid_loader, total=len(valid_loader))
    for batch in tqdm_object:
        batch = {k: v.to(CFG.device) for k, v in batch.items() if k != "caption"}
        loss = model(batch)

        count = batch["image"].size(0)
        loss_meter.update(loss.item(), count)

        tqdm_object.set_postfix(valid_loss=loss_meter.avg)
    return loss_meter


def main():
    train_df, valid_df = make_train_valid_dfs()
    tokenizer = DistilBertTokenizer.from_pretrained(CFG.text_tokenizer)
    train_loader = build_loaders(train_df, tokenizer, mode="train")
    valid_loader = build_loaders(valid_df, tokenizer, mode="valid")


    model = CLIPModel().to(CFG.device)
    params = [
        {"params": model.image_encoder.parameters(), "lr": CFG.image_encoder_lr},
        {"params": model.text_encoder.parameters(), "lr": CFG.text_encoder_lr},
        {"params": itertools.chain(
            model.image_projection.parameters(), model.text_projection.parameters()
        ), "lr": CFG.head_lr, "weight_decay": CFG.weight_decay}
    ]
    optimizer = torch.optim.AdamW(params, weight_decay=0.)
    lr_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", patience=CFG.patience, factor=CFG.factor
    )
    step = "epoch"

    best_loss = float('inf')
    for epoch in range(CFG.epochs):
        print(f"Epoch: {epoch + 1}")
        model.train()
        train_loss = train_epoch(model, train_loader, optimizer, lr_scheduler, step)
        model.eval()
        with torch.no_grad():
            valid_loss = valid_epoch(model, valid_loader)

        if valid_loss.avg < best_loss:
            best_loss = valid_loss.avg
            torch.save(model.state_dict(), "best.pt")
            print("Saved Best Model!")

        lr_scheduler.step(valid_loss.avg)

"""Running the next cell start training the model. Put the kernel on GPU mode. Every epoch should take about 8 minutes on GPU if you are using 8k version (even one epoch is enough!). It can take some seconds before training actually starts because we are going to encode all the captions once in the train and valid dataset, so please don't stop it! Every thing is working fine."""

main()

"""## Inference

Okay! We are done with training the model. Now, we need to do inference which in our case will be giving the model a piece of text and want it to retrieve the most relevant images from an unseen validation (or test) set.

### Getting Image Embeddings

In this function, we are loading the model that we saved after training, feeding it images in validation set and returning the image_embeddings with shape (valid_set_size, 256) and the model itself.
"""

def get_image_embeddings(valid_df, model_path):
    tokenizer = DistilBertTokenizer.from_pretrained(CFG.text_tokenizer)
    valid_loader = build_loaders(valid_df, tokenizer, mode="valid")

    model = CLIPModel().to(CFG.device)
    model.load_state_dict(torch.load(model_path, map_location=CFG.device))
    model.eval()

    valid_image_embeddings = []
    with torch.no_grad():
        for batch in tqdm(valid_loader):
            image_features = model.image_encoder(batch["image"].to(CFG.device))
            image_embeddings = model.image_projection(image_features)
            valid_image_embeddings.append(image_embeddings)
    return model, torch.cat(valid_image_embeddings)

_, valid_df = make_train_valid_dfs()
model, image_embeddings = get_image_embeddings(valid_df, "best.pt")

valid_df.head()

# save mode
torch.save(model.state_dict(), '/content/drive/My Drive/Finalsimplemodel.pth')

"""### Finding Matches

This function does the final task that we wished our model would be capable of: it gets the model, image_embeddings, and a text query. It will display the most relevant images from the validation set! Isn't it amazing? Let's see how it performs after all!
"""

def find_matches(model, image_embeddings, query, image_filenames, n=9):
    tokenizer = DistilBertTokenizer.from_pretrained(CFG.text_tokenizer)
    encoded_query = tokenizer([query])
    batch = {
        key: torch.tensor(values).to(CFG.device)
        for key, values in encoded_query.items()
    }
    with torch.no_grad():
        text_features = model.text_encoder(
            input_ids=batch["input_ids"], attention_mask=batch["attention_mask"]
        )
        text_embeddings = model.text_projection(text_features)

    image_embeddings_n = F.normalize(image_embeddings, p=2, dim=-1)
    text_embeddings_n = F.normalize(text_embeddings, p=2, dim=-1)
    dot_similarity = text_embeddings_n @ image_embeddings_n.T

    values, indices = torch.topk(dot_similarity.squeeze(0), n * 5)
    matches = [image_filenames[idx] for idx in indices[::5]]

    _, axes = plt.subplots(3, 3, figsize=(10, 10))
    for match, ax in zip(matches, axes.flatten()):
        image = cv2.imread(f"{CFG.image_path}/{match}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        ax.imshow(image)
        ax.axis("off")

    plt.show()

#_, valid_df = make_train_valid_dfs()
selected_rows = df[df["activity_name"] == "com.wanderu.wanderu"]

df2=df.head(500)

model, image_embeddings = get_image_embeddings(selected_rows, "/content/drive/My Drive/Finalsimplemodel.pth")

selected_rows

import shutil

# Unzip the testImages.zip file into a temporary folder
temp_folder = '/content/temp_extracted'
!unzip -q /content/drive/MyDrive/testImages.zip -d {temp_folder}

# Move the contents of the temporary folder to /content/trainImages
destination_folder = '/content/trainImages'
for item in os.listdir(temp_folder):
    source = os.path.join(temp_folder, item)
    destination = os.path.join(destination_folder, item)
    shutil.move(source, destination)

# Clean up the temporary folder
shutil.rmtree(temp_folder)

print("Contents moved to /content/trainImages.")

!unzip /content/drive/MyDrive/testImages.zip -d /content/trainImages

# test
model_path="/content/drive/My Drive/Finalsimplemodel.pth"
model = CLIPModel().to(CFG.device)
model.load_state_dict(torch.load(model_path, map_location=CFG.device))
model.eval()
tokenizer = DistilBertTokenizer.from_pretrained(CFG.text_tokenizer)

def get_image_embeddings_within_app(valid_df):
    valid_loader = build_loaders(valid_df, tokenizer, mode="valid")
    valid_image_embeddings = []
    with torch.no_grad():
        for batch in tqdm(valid_loader):
            image_features = model.image_encoder(batch["image"].to(CFG.device))
            #print(image_features)
            image_embeddings = model.image_projection(image_features)
            #print(image_embeddings)
            valid_image_embeddings.append(image_embeddings)
            #print(valid_image_embeddings)
    return torch.cat(valid_image_embeddings)

grouped_df = df.groupby('activity_name')

for activity_name, activity_group_df in grouped_df:
     image_ids = activity_group_df['image'].unique().tolist()
     image_ids = image_ids[:8]
     sampled_images_df = activity_group_df[activity_group_df['image'].isin(image_ids)]

query='add icon and download option in bible reading tracking app'

actual_image = activity_group_df[activity_group_df['caption'] == query]['image'].iloc[0]

image_filenames

import random

def find_matches_score_all(model, df, k=2,M=6):
    tokenizer = DistilBertTokenizer.from_pretrained(CFG.text_tokenizer)

    #image_filenames = df['image'].values
    total_queries = len(df)  # Total number of queries

    cumulative_score = 0  # Initialize cumulative score
    ground_truth_list = []  # List to store ground truth labels
    prediction_list = []     # List to store model predictions
    grouped_df = df.groupby('activity_name')

    for activity_name, activity_group_df in grouped_df:
        print(f"Activity Name: {activity_name}")
        # Get unique image IDs for this activity group
        image_ids = activity_group_df['image'].unique().tolist()
        # If the activity group has fewer than M images, sample from other groups
        if len(image_ids) < M:
            other_groups = [other_group_df for other_activity, other_group_df in grouped_df if other_activity != activity_name]
            other_image_ids = [id for other_group_df in other_groups for id in other_group_df['image'].unique()]
            sampled_ids = random.sample(other_image_ids, min(M - len(image_ids), len(other_image_ids)))
            image_ids.extend(sampled_ids)

        # Convert the set of unique image IDs back to a list
        image_ids = image_ids[:M]
        sampled_images_df = df[df['image'].isin(image_ids)]
        image_filenames = sampled_images_df.values
        print(' image file names is :',image_filenames)
        image_embeddings = get_image_embeddings_within_app(sampled_images_df)

        # Loop through captions for this activity group
        captions = activity_group_df['caption'].tolist()
        for query in captions:
            # Filter the DataFrame to find the actual image based on the caption
            actual_image = activity_group_df[activity_group_df['caption'] == query]['image'].iloc[0]
            print(' actual image  is :',actual_image)
            print(' caption is :', query)
            print(' actual image is :', actual_image)
            print('test images are :',image_ids)
            encoded_query = tokenizer([query], padding=True, truncation=True, return_tensors="pt")
            batch = {key: tensor.to(CFG.device) for key, tensor in encoded_query.items()}

            with torch.no_grad():
                text_features = model.text_encoder(
                    input_ids=batch["input_ids"], attention_mask=batch["attention_mask"]
                )
                text_embeddings = model.text_projection(text_features)

            image_embeddings_n = F.normalize(image_embeddings, p=2, dim=-1)
            text_embeddings_n = F.normalize(text_embeddings, p=2, dim=-1)
            dot_similarity = text_embeddings_n @ image_embeddings_n.T
            values, indices = torch.topk(dot_similarity.squeeze(0), k*5)
            print(' value k is :',values)
            matches = [image_filenames[idx] for idx in indices[::5]]
            top_matches = matches  # Get the top k matches
            predictions_k = matches[0]  # Predicted image names
            print(' prediction k is :',predictions_k)
            prediction_list.append(predictions_k[0])  # Store the predicted image filename
            #prediction_list.append(predictions_k)  # Store the model predictions

            score = 1 if actual_image in predictions_k else 0  # Calculate the score
            cumulative_score += score  # Update cumulative score

            ground_truth_list.append(actual_image)  # Store the ground truth label
            print(f"Caption: {query}, Actual Image: {actual_image}, Top Matches: {predictions_k},  Score: {score}")

    final_score = cumulative_score / len(df)  # Calculate final score
    print(f"Final Score: {cumulative_score}")
    print(f"Final Score: {final_score}")
    return final_score,ground_truth_list, prediction_list

df2=df.head(100)

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# final_score,ground_truth, predictions = find_matches_score_all(model, df, k=1,M=6)

predictions

captions = df.groupby('activity_name')

android_captions = df[df['activity_name']=='android']
android_captions

captions = df.groupby('image')['caption'].first().reset_index()
image_filenames = selected_rows['image'].values
find_matches_with_score(model, image_embeddings, captions, image_filenames, n=3)

image_filenames=selected_rows['image'].values
image_filenames

def find_matches(model, image_embeddings, query, image_filenames, n=9):
    tokenizer = DistilBertTokenizer.from_pretrained(CFG.text_tokenizer)
    encoded_query = tokenizer([query])
    batch = {
        key: torch.tensor(values).to(CFG.device)
        for key, values in encoded_query.items()
    }
    with torch.no_grad():
        text_features = model.text_encoder(
            input_ids=batch["input_ids"], attention_mask=batch["attention_mask"]
        )
        text_embeddings = model.text_projection(text_features)

    image_embeddings_n = F.normalize(image_embeddings, p=2, dim=-1)
    text_embeddings_n = F.normalize(text_embeddings, p=2, dim=-1)
    dot_similarity = text_embeddings_n @ image_embeddings_n.T

    values, indices = torch.topk(dot_similarity.squeeze(0), n * 5)
    matches = [image_filenames[idx] for idx in indices[::5]]

    _, axes = plt.subplots(3, 3, figsize=(10, 10))
    for match, ax in zip(matches, axes.flatten()):
        image = cv2.imread(f"{CFG.image_path}/{match}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        ax.imshow(image)
        ax.axis("off")

    plt.show()

find_matches(model,
             image_embeddings,
             query="page showing you have not booked any trip in application",
             image_filenames=selected_rows['image'].values,
             n=3)

find_matches(model,
             image_embeddings,
             query="screen showing list of various countries for an app",
             image_filenames=valid_df['image'].values,
             n=9)

valid_df['image'].values

selected_rows = df[df["activity_name"] == "com.android.contacts"]

selected_rows.shape

selected_rows.head()

find_matches(model,
             image_embeddings,
             query="display of a footwear options in a shopping app",
             image_filenames=valid_df['image'].values,
             n=9)

find_matches(model,
             image_embeddings,
             query="list of diet plans showing in application",
             image_filenames=valid_df['image'].values,
             n=9)

find_matches(model,
             image_embeddings,
             query="pop up displaying introduction for the app",
             image_filenames=valid_df['image'].values,
             n=9)

image_folder_path = '/content/drive/MyDrive/test'
caption_file_path = '/content/captions.csv'

image = cv2.imread("/content/drive/MyDrive/test/31677.jpg")
cv2_imshow(image)

def get_image_embeddings(valid_df, model_path):
    tokenizer = DistilBertTokenizer.from_pretrained(CFG.text_tokenizer)
    valid_loader = build_loaders(valid_df, tokenizer, mode="valid")
    model = CLIPModel().to(CFG.device)
    model.load_state_dict(torch.load(model_path, map_location=CFG.device))
    model.eval()

    valid_image_embeddings = []
    with torch.no_grad():
        for batch in tqdm(valid_loader):
            image_features = model.image_encoder(batch["image"].to(CFG.device))
            print(image_features)
            image_embeddings = model.image_projection(image_features)
            print(image_embeddings)
            valid_image_embeddings.append(image_embeddings)
            print(valid_image_embeddings)
    return model, torch.cat(valid_image_embeddings)

df.head(10)

df.shape

import pandas as pd
import matplotlib.pyplot as plt

app_screen_counts = df['activity_name'].value_counts()

app_screen_counts.shape
# number of unique apps

app_screen_counts.head(20)

app_screen_counts = pd.DataFrame(app_screen_counts)
new_columns = ['screen_shots_counts']

# Reset column names
app_screen_counts.columns = new_columns
app_screen_counts.reset_index(inplace=True)

# Rename the 'index' column to 'image count'
app_screen_counts.rename(columns={'index': 'app name'}, inplace=True)
app_screen_counts.head(20)

screencounts = df['activity_name'].value_counts()

unique_counts=screencounts.unique()
unique_counts

screen_app_count=app_screen_counts['screen_shots_counts'].value_counts()

screen_app_count = pd.DataFrame(screen_app_count)
new_columns = ['no. of apps has this no. of screen count']
screen_app_count.columns = new_columns

screen_app_count.reset_index(inplace=True)

# Rename the 'index' column to 'image count'
screen_app_count.rename(columns={'index': 'no. of screenshots'}, inplace=True)
screen_app_count.head(20)

screen_app_count.shape

screen_app_count.head(39)

ground_truth, predictions = find_matches_within_app(model, image_embeddings, df, n=1,M=6,k=1)

import torch
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, top_k_accuracy_score

accuracy = accuracy_score(ground_truth, predictions)

accuracy

precision = precision_score(ground_truth, predictions, average='weighted')
precision

recall = recall_score(ground_truth, predictions, average='micro')
f1 = f1_score(ground_truth, predictions, average='micro')
recall

f1 = f1_score(ground_truth, predictions, average='micro')
f1

final_score